# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "hashicorp-education/ubuntu-24-04"
    ubuntu1.vm.box_version = "0.1.0"
    ubuntu1.vm.hostname = "ubuntu1.local"
    ubuntu1.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "hashicorp-education/ubuntu-24-04"
    ubuntu2.vm.box_version = "0.1.0"
    ubuntu2.vm.hostname = "ubuntu2.local"
    ubuntu2.vm.network "private_network", type: "dhcp"
  end
end
